name: README Example
"on":
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm ci --production
      - run: node index.js
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
